config/routes.rb
Rails.application.routes.draw do

  # Home page and sitemap routes
  root to: redirect('https://ucmo.primo.exlibrisgroup.com/discovery/search?vid=01UCMO_INST:jckl_custom')
  get 'index', to: redirect('https://ucmo.primo.exlibrisgroup.com/discovery/search?vid=01UCMO_INST:jckl_custom')

  # Hours routes
  resources :library_hours, only: [:index], path: 'hours'

  # News routes REDIRECT
  resources :news_items, path: 'news', only: [:index, :show], param: :friendly_url

  # Database routes  get 'databases', to: redirect('http://guides.library.ucmo.edu/az.php')
  get 'databases', to: redirect('http://guides.library.ucmo.edu/az.php')

  # Employee routes
  get 'employees/absence', to: 'absences#new', as: 'legacy_absence' #redirect old absence form route
  get 'employees/index', to: redirect('https://guides.library.ucmo.edu/employees') # redirect old employee directory
  get 'employees', to: redirect('https://guides.library.ucmo.edu/employees') # redirect old employee directory

  get 'scdps', to: 'employees#scdps'
  resources :employees, except: :index, param: :name do
    collection do
      get 'portal'
      get 'student-workers', to: 'employees#student_workers'
    end

    resources :absences do
      patch 'approve', on: :member
      patch 'reject', on: :member
      patch 'receive_note', on: :member
    end
  end
  get 'absences', to: 'absences#by_date', as: 'absences_by_date'
  get 'absences/:date', to: 'absences#by_date'

  resources :absences, only: [:new, :create, :index]


  # Contact routes REDIRECT
  resources :website_contacts, path: 'contact', only: [:create] do
    collection do
      get 'general'
      get 'employee/:name', action: 'employee', as: 'employee'
      get 'office/:name', action: 'office', as: 'office'
      get 'info'
    end
  end
  get 'contact', to: 'website_contacts#general'
  get 'contact/chat', to: 'website_contacts#chat'
  get 'chat', to: 'website_contacts#chat'

  # Map routes REDIRECT
  get 'map', to: 'map#index', as: 'map'
  get 'map/index', to: 'map#index'

  # Room booking routes
  get 'room-bookings', to: redirect('https://ucmo.libcal.com/reserve/jckl-rooms'), as: 'meeting_rooms' #old url redirect
  get 'roomschedules', to: redirect('https://ucmo.libcal.com/reserve/jckl-rooms') # old url redirect


  # New books routes REDIRECT
  resources :new_books, path: 'new-books', only: [:index] do
    get 'mappings', on: :collection
  end
  get 'newbooks', to: 'new_books#index'

  # Purchase request routes REDIRECT
  resources :new_book_requests, path: 'purchase-request', only: [:new, :create]
  get 'purchase-request', to: 'new_book_requests#new'

  # DVD routes REDIRECT
  get 'dvds', to: 'dvds#index', as: 'dvds'
  get 'dvds/index', to: 'dvds#index'

  # Stats routes
  get 'stats', to: 'stats#dashboard'
  get 'stats/dashboard', to: 'stats#dashboard', as: 'stats_dashboard'
  get 'stats/headcount_form', to: 'stats#headcount_form', as: 'stats_headcount_form'
  post 'stats/headcount_form', to: 'stats#headcount_form'
  get 'stats/headcounts', to: 'stats#headcounts', as: 'stats_headcounts'
  get 'stats/studyrooms', to: 'stats#studyrooms', as: 'stats_studyrooms'
  get 'stats/computers', to: 'stats#computers', as: 'stats_computers'

  # CLF routes
  get 'clf', to: redirect('http://clf.ucmo.edu')
  get 'clf/index', to: redirect('http://clf.ucmo.edu')
  get 'clf/books', to: 'clf#books_feed'
  get 'clf/browse'
  post 'clf/add_to_cart', as: 'clf_add_to_cart'
  get 'clf/cart', as: 'clf_cart'
  get 'clf/order', as: 'clf_order'
  post 'clf/order'

  # Tools routes
  get 'tools/callnumber-parser', to: 'tools#callnumber_parser'
  post 'tools/callnumber-parser', to: 'tools#callnumber_parser'
  post 'tools/calendar_sync', to: 'tools#calendar_sync'

  # File upload routes
  resources :files

  # Horses in Culture routes
  get 'horses_in_culture/data', to: 'horses_in_culture#data', as: 'horses_in_culture_data'

  # Error handling
  match '/401', to: 'errors#unauthorized', via: :all, as: 'error_unauthorized'
  match '/404', to: 'errors#not_found', via: :all, as: 'error_not_found'
  match '/422', to: 'errors#unprocessable', via: :all, as: 'error_unprocessable'
  match '/500', to: 'errors#internal_server_error', via: :all, as: 'error_internal_server_error'
  match '/ezproxy-error', to:'errors#ezproxy', via: :post, as: 'error_ezproxy'

  # Page element routes
  get 'api/ucm_header', to: 'api#ucm_header'
  get 'api/ucm_footer', to: 'api#ucm_footer'

  # API routes MERGE WITH ELEMENTS
  get 'api/nav', to: 'api#nav'

  # Assets handling
  get 'css/:file', to: 'assets#css'
  get 'js/:file', to: 'assets#js'
  get 'img/:file', to: 'assets#img'

  # Devise and ActiveAdmin authentication
  devise_config = ActiveAdmin::Devise.config
  devise_config[:controllers][:omniauth_callbacks] = 'omniauth_callbacks'
  devise_config[:controllers][:registrations] = 'devise/registrations'
  devise_config[:controllers][:sessions] = 'sessions'
  devise_for :users, devise_config
  ActiveAdmin.routes(self)
  get 'omniauth_callbacks/all'
end

app/models/meeting_room.rb
class MeetingRoom < ApplicationRecord
  has_many :meeting_room_bookings, dependent: :nullify

  has_attached_file :photo,
                    styles: {
                      medium: '400x400'
                    }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator, attributes: :photo, less_than: 10.megabytes

  GOOGLE_CALENDAR_EMBED_BASE_URL = 'https://www.google.com/calendar/embed?showCurrentTime=0showSubscribeButton=0&showTz=0&showPrint=0&showTabs=0&showCalendars=0&wkst=1&bgcolor=%23e2e2e2&ctz=America%2FChicago'.freeze
  GOOGLE_CALENDAR_PAGE_BASE_URL = 'http://www.google.com/calendar/embed?mode=WEEK&ctz=America/Chicago'.freeze
  GOOGLE_CALENDAR_AVAILABILITY_BASE_URL = "https://www.googleapis.com/calendar/v3/freeBusy".freeze

  def google_calendar_week_embed
    "#{GOOGLE_CALENDAR_EMBED_BASE_URL}&src=#{google_calendar_id}&mode=WEEK"
  end

  def google_calendar_week_page
    "#{GOOGLE_CALENDAR_PAGE_BASE_URL}&src=#{google_calendar_id}&mode=WEEK"
  end

  def medium_photo_url
    self.photo&.url(:medium)
  end

  def bookings(start_time, end_time)
    api_service = GoogleApiService.new
    bookings = api_service.get_gcal_events(self.google_calendar_id, start_time, end_time)
  end

  def available?(start_time, end_time)
    bookings = self.bookings(start_time - 1.day, end_time + 1.day)
    concurrent_bookings = bookings.select do |b|
      (start_time <= b.start.date_time && end_time > b.start.date_time && end_time <= b.end.date_time) ||
      (start_time >= b.start.date_time && end_time <= b.end.date_time) ||
      (start_time >= b.start.date_time && start_time < b.end.date_time && end_time >= b.end.date_time)
    end
    concurrent_bookings.blank?
  end

end

app/views/meeting_rooms/index.html.erb
<h1><%= @page_title %></h1>

<% if !current_user %>
<div class="alert alert-warning">
  Note: Anyone can view the room schedules below, but only library employees are able to book rooms using this system.
  If you are not a library employee, please use <%= link_to "25Live", "http://www.ucmo.edu/25/25" %>. If you are a library employee, please <%= link_to "log in", new_user_session_url %>.
</div>
<% end %>

<div>
  <%= form_tag(meeting_rooms_url, method: :get, class: 'room-bookings-availability-filter form-inline') do -%>
    <p class="w-100">Looking for a room at a specific time? Enter the time for your event here.</p>
    <label htmlFor="start-time">Start Time</label>
    <input type="text" class="form-control anytime-datetime" name="start_time" id="start-time" value="<%= params[:start_time] %>" />
    <label htmlFor="end-time">End Time</label>
    <input type="text" class="form-control anytime-datetime" name="end_time" id="end-time" value="<%= params[:end_time] %>" />
    <button class="btn btn-primary" type="submit">Submit</button>
    <%= link_to 'Clear', meeting_rooms_url, class: 'btn btn-light' %>
  <% end -%>

  <div class="room-bookings-availability-message">
    <% if @rooms.blank? %>
      <div class="alert alert-warning">There are no rooms available during the specified time.</div>
    <% elsif (params[:start_time] || params[:end_time]) && !(params[:start_time] && params[:end_time]) %>
      <div class="alert alert-warning">Please enter a start time and an end time.</div>
    <% elsif (params[:start_time] && params[:end_time]) %>
      <div class="alert alert-success">There are <%= @rooms.length %> rooms available during the specified time.</div>
    <% end %>
  </div>

  <ul class="room-bookings-room-list list-group">
    <% @rooms&.each do |room| %>
      <li id="room-<%= room.room_name %>" class="list-group-item room">
        <div class="w-100">
          <h2 class="room-name"><%= room.display_name %></h2>
          <div class="room-description"><%= room.description %></div>
        </div>
        <div class="row">
          <div class="room-booking-info col-md-4">
            <table class="table table-sm table-striped">
              <tbody>
                <tr>
                  <td>Seats</td>
                  <td><%= room.seating %></td>
                </tr>
                <tr>
                  <td>Desktops</td>
                  <td><%= room.desktops %></td>
                </tr>
                <tr>
                  <td>Laptops</td>
                  <td><%= room.laptops %></td>
                </tr>
                <tr>
                  <td>Projector</td>
                  <td>
                    <% if room.projector %>
                      <i class="fa fa-check-square">
                    <% else %>
                      <i class="fa fa-times-rectangle">
                    <% end %>
                  </td>
                </tr>
                <tr>
                  <td>Podium</td>
                  <td>
                    <% if room.projector %>
                      <i class="fa fa-check-square">
                    <% else %>
                      <i class="fa fa-times-rectangle">
                    <% end %>
                  </td>
                </tr>
                <tr>
                  <td>Whiteboard</td>
                  <td>
                    <% if room.projector %>
                      <i class="fa fa-check-square">
                    <% else %>
                      <i class="fa fa-times-rectangle">
                    <% end %>
                  </td>
                </tr>
                <tr>
                  <td>Classroom Use</td>
                  <td>
                    <% if room.projector %>
                      <i class="fa fa-check-square">
                    <% else %>
                      <i class="fa fa-times-rectangle">
                    <% end %>
                  </td>
                </tr>
                <tr>
                  <td>Meetings</td>
                  <td>
                    <% if room.projector %>
                      <i class="fa fa-check-square">
                    <% else %>
                      <i class="fa fa-times-rectangle">
                    <% end %>
                  </td>
                </tr>
                <% if room.library_only %>
                <tr>
                  <td>Library use only</td>
                  <td><i class="fa fa-exclamation-triangle"></i></td>
                </tr>
                <% elsif room.faculty_staff_only %>
                <tr>
                  <td>Faculty and staff only</td>
                  <td><i class="fa fa-exclamation-triangle"></i></td>
                </tr>
                <% else %>
                <tr>
                  <td>Faculty, staff, and students</td>
                  <td><i class="fa fa-check-square"></i></td>
                </tr>
                <% end %>

              </tbody>
            </table>
          </div>
          <div class="col-md-4">
            <% if room.photo %>
              <div><img class="room-image" src="<%= room.medium_photo_url %>" /></div>
            <% else %>
              <p>(Photo not available.)</p>
            <% end %>
          </div>
          <div class="room-booking-buttons col-md-4">
            <a class="room-calendar-link btn btn-lg btn-default" data-toggle="modal" data-target="#room-bookings-calendar-modal" data-calendar-url="<%= room.google_calendar_week_page %>" data-calendar-embed-url="<%= room.google_calendar_week_embed %>">View Calendar</a>
            <%= link_to 'View on Map', map_url(highlight: 'room-' + room.room_name), class: 'room-map btn btn-lg btn-light' %>
            <% if current_user.present? %>
              <%= link_to 'Reserve This Room', new_booking_for_meeting_room_url(room_name: room.room_name), class: 'room-book btn btn-lg btn-light' %>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>

  <div class="room-bookings-calendar-modal modal" id="room-bookings-calendar-modal" tabIndex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h2 class="modal-title"></h2>
        </div>
        <div class="modal-body">
          <iframe class="room-bookings-iframe" scrolling="no"></iframe>
          <p class="google-calendar-link">Having trouble viewing this calendar?
            <a href="">View the calendar on Google.</a>
          </p>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/meeting_rooms/new.html.erb
<h1><%= @page_title %></h1>

<p>
  University of Central Missouri faculty, staff, and students may reserve available rooms in the James C. Kirkpatrick Library by going through 25Live (if you have had training with Meeting & Conference Services) or by contacting Meeting & Conference Services at 660-543-4342, email <a href="mailto:unionmacs@ucmo.edu">unionmacs@ucmo.edu</a> or web site at <a href="http://www.ucmo.edu/offices/meeting-and-conference-services/">www.ucmo.edu/offices/meeting-and-conference-services/</a>.  Only Library Services personnel are authorized to use the booking form.
</p>
<h2>Scheduling</h2>
<p>
  Reservations must be made in advance by using 25Live or by contacting Meeting & Conference Services at 660-543-4342, email <a href="mailto:unionmacs@ucmo.edu">unionmacs@ucmo.edu</a> or web site at <a href="http://www.ucmo.edu/offices/meeting-and-conference-services/">www.ucmo.edu/offices/meeting-and-conference-services/</a>. UCM faculty, staff and students have priority in the use of the facilities over general community events. Community patrons are assessed a room rental fee. Please call Meeting & Conference Services at 660-543-4342, email unionmacs@ucmo.edu or web site www.ucmo.edu/offices/meeting-and-conference-services/ or stop by the Union room 301 for room rental rates.
</p>
<h2>Special Arrangements</h2>
<p>
  The University Librarian determines which rooms are available for food and drinks. Only events that have been previously arranged with the University Librarian may have food and drinks. The requestor is responsible to see that this request is followed. University policy requires the use of Sodexo for food and refreshments. Food services may be contacted at 660-543-4440, email <a href="mailto:sodexcatering@ucmo.edu">sodexcatering@ucmo.edu</a> or web site at <a href="http://www.ucmo.edu/offices/elliott-student-union/retail-dining/">www.ucmo.edu/offices/elliott-student-union/retail-dining/</a>. Food cannot be delivered prior to the opening of the facility. Library personnel does not arrange for set up. All set up is the responsibility of the user.
</p>
<p>
  The user is responsible for setting up any special arrangements for furniture. Please call Meeting & Conference Services at 660-543-4342, email <a href="mailto:unionmacs@ucmo.edu">unionmacs@ucmo.edu</a>, web site <a href="http://www.ucmo.edu/offices/meeting-and-conference-services/">www.ucmo.edu/offices/meeting-and-conference-services/</a> or stop by the Union Room 301 for room arrangements. A cleaning fee may be charged if the room/area is not returned to its original condition.
</p>
<p>
  If special software is needed, the requestor must contact the Office of Technology at 660-543-4357 to request software. Library Services does not provide specialty software.
</p>

<h2>Booking Form</h2>
<% if @booking.errors.any? %>
  <div class="form-errors alert alert-danger">
    <h2>Please correct the following errors:</h2>
    <ul>
      <% @booking.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= semantic_form_for(@booking, url: create_booking_for_meeting_room_url(room_name: @booking.meeting_room&.room_name)) do |f| %>
  <%= f.inputs do %>
    <%= f.input :contact_name, as: :string, label: "Name" %>
    <%= f.input :contact_email, as: :email, label: "Email Address" %>
    <%= f.input :contact_phone, as: :string, label: "Phone Number" %>
    <%= f.input :contact_address, as: :string, label: "Address" %>
    <%= f.input :contact_dept, as: :string, label: "Department/Organization" %>
    <%= f.input :meeting_room, as: :select, label: "Room", collection: MeetingRoom.all.order(:display_name).pluck(:display_name, :id) ,input_html: {disabled: true} %>
    <%= f.input :event_name, as: :string, label: "Event Title" %>
    <%= f.input :start_time, as: :string, label: "Booking Start Time", input_html: { class: "anytime-datetime" } %>
    <%= f.input :end_time, as: :string, label: "Booking End Time", input_html: { class: "anytime-datetime" } %>
    <%= f.input :setup_time, as: :select, label: "Setup Time", collection: ["0 minutes", "15 minutes", "30 minutes", "45 minutes", "60 minutes"] %>
    <%= f.input :takedown_time, as: :select, label: "Takedown Time", collection: ["0 minutes", "15 minutes", "30 minutes", "45 minutes", "60 minutes"] %>
    <%= f.input :attendance, as: :number, label: "Estimated Attendance" %>
    <%= f.input :recurrence, as: :text, label: "How often will this meeting recur? (if applicable)", input_html: { rows: "4" } %>
    <%= f.input :notes, as: :text, label: "Additional Information", input_html: { rows: "4" } %>
  <% end %>
  <p>By submitting this request, you have read and hereby agree to the guidelines as outlined above.</p>
  <%= f.actions do %>
    <%= f.action :submit, as: :button, label: "Submit", button_html: {class: 'btn btn-primary'} %>
  <% end %>
<% end %>