config/routes.rb
Rails.application.routes.draw do

  # Home page and sitemap routes
  root to: redirect('https://ucmo.primo.exlibrisgroup.com/discovery/search?vid=01UCMO_INST:jckl_custom')
  get 'index', to: redirect('https://ucmo.primo.exlibrisgroup.com/discovery/search?vid=01UCMO_INST:jckl_custom')

  # Hours routes
  resources :library_hours, only: [:index], path: 'hours'

  # News routes REDIRECT
  resources :news_items, path: 'news', only: [:index, :show], param: :friendly_url

  # Database routes  get 'databases', to: redirect('http://guides.library.ucmo.edu/az.php')
  get 'databases', to: redirect('http://guides.library.ucmo.edu/az.php')

  # Employee routes
  get 'employees/absence', to: 'absences#new', as: 'legacy_absence' #redirect old absence form route
  get 'employees/index', to: redirect('https://guides.library.ucmo.edu/employees') # redirect old employee directory
  get 'employees', to: redirect('https://guides.library.ucmo.edu/employees') # redirect old employee directory

  get 'scdps', to: 'employees#scdps'
  resources :employees, except: :index, param: :name do
    collection do
      get 'portal'
      get 'student-workers', to: 'employees#student_workers'
    end

    resources :absences do
      patch 'approve', on: :member
      patch 'reject', on: :member
      patch 'receive_note', on: :member
    end
  end
  get 'absences', to: 'absences#by_date', as: 'absences_by_date'
  get 'absences/:date', to: 'absences#by_date'

  resources :absences, only: [:new, :create, :index]


  # Contact routes REDIRECT
  resources :website_contacts, path: 'contact', only: [:create] do
    collection do
      get 'general'
      get 'employee/:name', action: 'employee', as: 'employee'
      get 'office/:name', action: 'office', as: 'office'
      get 'info'
    end
  end
  get 'contact', to: 'website_contacts#general'
  get 'contact/chat', to: 'website_contacts#chat'
  get 'chat', to: 'website_contacts#chat'

  # Map routes REDIRECT
  get 'map', to: 'map#index', as: 'map'
  get 'map/index', to: 'map#index'

  # Room booking routes
  get 'room-bookings', to: redirect('https://ucmo.libcal.com/reserve/jckl-rooms'), as: 'meeting_rooms' #old url redirect
  get 'roomschedules', to: redirect('https://ucmo.libcal.com/reserve/jckl-rooms') # old url redirect


  # New books routes REDIRECT
  resources :new_books, path: 'new-books', only: [:index] do
    get 'mappings', on: :collection
  end
  get 'newbooks', to: 'new_books#index'

  # Purchase request routes REDIRECT
  resources :new_book_requests, path: 'purchase-request', only: [:new, :create]
  get 'purchase-request', to: 'new_book_requests#new'

  # DVD routes REDIRECT
  get 'dvds', to: 'dvds#index', as: 'dvds'
  get 'dvds/index', to: 'dvds#index'

  # Stats routes
  get 'stats', to: 'stats#dashboard'
  get 'stats/dashboard', to: 'stats#dashboard', as: 'stats_dashboard'
  get 'stats/headcount_form', to: 'stats#headcount_form', as: 'stats_headcount_form'
  post 'stats/headcount_form', to: 'stats#headcount_form'
  get 'stats/headcounts', to: 'stats#headcounts', as: 'stats_headcounts'
  get 'stats/studyrooms', to: 'stats#studyrooms', as: 'stats_studyrooms'
  get 'stats/computers', to: 'stats#computers', as: 'stats_computers'

  # CLF routes
  get 'clf', to: redirect('http://clf.ucmo.edu')
  get 'clf/index', to: redirect('http://clf.ucmo.edu')
  get 'clf/books', to: 'clf#books_feed'
  get 'clf/browse'
  post 'clf/add_to_cart', as: 'clf_add_to_cart'
  get 'clf/cart', as: 'clf_cart'
  get 'clf/order', as: 'clf_order'
  post 'clf/order'

  # Tools routes
  get 'tools/callnumber-parser', to: 'tools#callnumber_parser'
  post 'tools/callnumber-parser', to: 'tools#callnumber_parser'
  post 'tools/calendar_sync', to: 'tools#calendar_sync'

  # File upload routes
  resources :files

  # Horses in Culture routes
  get 'horses_in_culture/data', to: 'horses_in_culture#data', as: 'horses_in_culture_data'

  # Error handling
  match '/401', to: 'errors#unauthorized', via: :all, as: 'error_unauthorized'
  match '/404', to: 'errors#not_found', via: :all, as: 'error_not_found'
  match '/422', to: 'errors#unprocessable', via: :all, as: 'error_unprocessable'
  match '/500', to: 'errors#internal_server_error', via: :all, as: 'error_internal_server_error'
  match '/ezproxy-error', to:'errors#ezproxy', via: :post, as: 'error_ezproxy'

  # Page element routes
  get 'api/ucm_header', to: 'api#ucm_header'
  get 'api/ucm_footer', to: 'api#ucm_footer'

  # API routes MERGE WITH ELEMENTS
  get 'api/nav', to: 'api#nav'

  # Assets handling
  get 'css/:file', to: 'assets#css'
  get 'js/:file', to: 'assets#js'
  get 'img/:file', to: 'assets#img'

  # Devise and ActiveAdmin authentication
  devise_config = ActiveAdmin::Devise.config
  devise_config[:controllers][:omniauth_callbacks] = 'omniauth_callbacks'
  devise_config[:controllers][:registrations] = 'devise/registrations'
  devise_config[:controllers][:sessions] = 'sessions'
  devise_for :users, devise_config
  ActiveAdmin.routes(self)
  get 'omniauth_callbacks/all'
end

app/views/index/index.html.erb
<h1 class="sr-only">James C. Kirkpatrick Library Home Page</h1>

<section class="index-search w-100">

  <div class="search-background-overlay"></div>
  <div class="container">

    <h2 class="sr-only">Search the Library</h2>
    <%= render partial: 'shared/legacy_search' %>
    <div class="search-options card clearfix">
      <div class="card-body">
        <h2 class="card-title">More Ways to Search</h2>
        <a class="card-link" href="http://guides.library.ucmo.edu/az.php">Browse Databases</a>
        <a class="card-link" href="https://ucmo.primo.exlibrisgroup.com/discovery/jsearch?vid=01UCMO_INST%3Ajckl_custom">Journal Directory</a>
        <a class="card-link" href="http://guides.library.ucmo.edu/">Research Guides</a>
        <a class="card-link" href="https://universityofcentralmissourilibrary.account.worldcat.org/profile">Interlibrary Loan</a>
        <a class="card-link" href="https://ucmo.primo.exlibrisgroup.com/discovery/citationlinker?vid=01UCMO_INST%3Ajckl_custom">Known Item Search</a>
        <a class="card-link" href="https://ucmo.primo.exlibrisgroup.com/discovery/account?vid=01UCMO_INST:jckl_custom&section=overview&lang=en">My Library Account</a>
      </div>
    </div>
  </div>
</section>


<section class="index-links w-100">
  <div class="container">
    <div class="card-deck">

      <div class="using-library-block card">
        <h2 class="sr-only">Use the Library</h2>
        <% if LibraryHour.hours_today&.hours_display_text %>
          <div class="card-body text-center">
            <h3 class="card-title"></i>Today's Hours</h3>
            <p class="today-hours-display card-text"><%= LibraryHour.hours_today&.hours_display_text %></p>
          </div>
        <% end %>
        <div class="list-group list-group-flush">
          <a href="<%= library_hours_url %>" class="list-group-item">
            <i class="fa fa-2x fa-calendar"></i>Full Calendar
          </a>
          <a href="http://ucmo.libcal.com/booking/jckl-study-rooms" class="list-group-item">
            <i class="fa fa-2x fa-users"></i>Study Rooms
          </a>

          <a href="https://ucmo.libcal.com/calendar/events" class="list-group-item">
            <i class="fa fa-2x fa-university"></i>Workshops
          </a>
          <!--
          <a href="http://guides.library.ucmo.edu/events" class="list-group-item">
            <i class="fa fa-ticket"></i>Upcoming Events At JCKL
          </a>
          -->
        </div>
      </div>

      <div class="help-block card">
        <h2 class="sr-only">Get Help</h2>
        <div class="card-body text-center">
          <h3 class="card-title">
            <a class="chat-button" href="#" data-turbolinks="false">
              <div class="chat-button-bg1"></div>
              <div class="chat-button-bg2"></div>
              <div class="chat-button-text"><i class="fa fa-comments"></i>Chat Online</div>
            </a>
            <div class="libchat-widget-button" id="libchat_f84b4c05a5033a01d65116d4ae2db4fe"></div><script type="text/javascript" src="//v2.libanswers.com/load_chat.php?hash=f84b4c05a5033a01d65116d4ae2db4fe"></script>
          </h3>
        </div>
        <div class="list-group list-group-flush">
          <a href="tel:660-543-4154" class="list-group-item">
            <i class="fa fa-2x fa-phone"></i>660-543-4154
          </a>
          <a href="sms:660-230-0011" class="list-group-item">
            <i class="fa fa-2x fa-envelope-o"></i>660-230-0011
          </a>

          <a href="https://guides.library.ucmo.edu/employees/liaisons" class="list-group-item">
            <i class="fa fa-2x fa-id-card-o"></i>Subject Specialists
          </a>
        </div>
      </div>

      <div class="news-block card">
        <h2 class="sr-only">JCKL News</h2>

        <div class="card-body text-center">
          <h3 class="card-title"></i>JCKL News</h3>
          <a class="card-link social-media-icon" href="https://www.facebook.com/JCKLibrary" title="Facebook"><i class="fa fa-facebook-square fa-2x"></i></a>
          <a class="card-link social-media-icon" href="https://twitter.com/jcklibrary" title="Twitter"><i class="fa fa-twitter fa-2x"></i></a>
          <a class="card-link social-media-icon" href="http://instagram.com/jcklibrary" title="Instagram"><i class="fa fa-instagram fa-2x"></i></a>
          <a class="card-link social-media-icon" href="https://www.youtube.com/user/JCKLibraryUCM" title="YouTube"><i class="fa fa-youtube-play fa-2x"></i></a>
        </div>

        <div class="list-group list-group-flush">
          <% NewsItem.current_news.first(6).each do |news_item| %>
            <%= link_to(news_item_url(friendly_url: news_item.friendly_url || news_item.set_friendly_url), class: 'list-group-item news-item clearfix', id: "news-item-#{news_item.id}") do %>
              <% if news_item.news_image.present? %>
                <%= image_tag(news_item.news_image.url(:medium), alt: news_item.title, class: 'news-image')  %>
              <% end %>
              <h3 class="news-title"><%= news_item.title %></h3>
              <% if news_item.teaser.present? %>
                <p class="news-text"><%= news_item.teaser %></p>
              <% end %>
            <% end %>
          <% end %>
          <%= link_to("More JCKL News", news_items_path, class: 'news-more list-group-item' ) %>
      </div>

    </div>
  </div>
</section>

<style>

  <% if @bg_image == 1 %>
  body{
    background: url(<%= image_url("bg1.jpg") %>) repeat-y center -130px;
  }
  <% elsif @bg_image == 2 %>
  body{
    background: url(<%= image_url("bg2.jpg") %>) repeat-y center -50px;
  }
  .index-new-books{
    opacity: 1 !important;
  }
  <% elsif @bg_image == 3 %>
  body{
    background: url(<%= image_url("bg3.jpg") %>) repeat-y center -550px;
  }
  .index-new-books{
    opacity: 1 !important;
  }
  <% end %>

</style>

<section class="index-new-books w-100">
  <div class="container">
    <div class="inner container">
      <div class="spacer" style="height: 100px;"></div>
    </div>
  </div>
</section>

app/views/index/sitemap.html.erb
<div class="page sitemap">
  <h1><%= page_title %></h1>
  <% NavigationMenuItem.roots.order( "position asc" ).each do |menu| %>
    <h2>
      <a <%= if menu.url then "href='#{menu.url}'".html_safe end %> <%= if menu.element_class then "class='#{menu.element_class}'".html_safe end %> <%= if menu.element_id then "id='#{menu.element_id}'".html_safe end %>>
        <%= menu.label.html_safe %>
      </a>
    </h2>
    <% if menu.children %>
      <% menu.children.order( "position asc" ).each do |child1| %>
        <h3>
          <a <%= if child1.url then "href='#{child1.url}'".html_safe end %> <%= if child1.element_class then "class='#{child1.element_class}'".html_safe end %> <%= if child1.element_id then "id='#{child1.element_id}'".html_safe end %>>
            <%= child1.label.html_safe %>
          </a>
        </h3>
        <% if child1.children %>
          <ul>
            <% child1.children.each do |child2| %>
              <li>
                <a <%= if child2.url then "href='#{child2.url}'".html_safe end %> <%= if child2.element_class then "class='#{child2.element_class}'".html_safe end %> <%= if child2.element_id then "id='#{child2.element_id}'".html_safe end %>>
                  <%= child2.label.html_safe %>
                </a>
              </li>
            <% end %>
          </ul>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/index/sitemap.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
  <urlset xmlns="http://www.google.com/schemas/sitemap/0.90">
    <url>
      <loc>https://library.ucmo.edu/</loc>
      <lastmod><%= Time.now.strftime( "%Y-%m-%d" ) %></lastmod>
      <changefreq>daily</changefreq>
      <priority>1</priority>
    </url>
    <% NavigationMenuItem.all.order( "label asc" ).each do |item| %>
      <% if item.url %>
        <url>
          <loc><%= item.url %></loc>
        </url>
      <% end %>
    <% end %>
  </urlset>