config/routes.rb
Rails.application.routes.draw do

  # Home page and sitemap routes
  root to: redirect('https://ucmo.primo.exlibrisgroup.com/discovery/search?vid=01UCMO_INST:jckl_custom')
  get 'index', to: redirect('https://ucmo.primo.exlibrisgroup.com/discovery/search?vid=01UCMO_INST:jckl_custom')

  # Hours routes
  resources :library_hours, only: [:index], path: 'hours'

  # News routes REDIRECT
  resources :news_items, path: 'news', only: [:index, :show], param: :friendly_url

  # Database routes  get 'databases', to: redirect('http://guides.library.ucmo.edu/az.php')
  get 'databases', to: redirect('http://guides.library.ucmo.edu/az.php')

  # Employee routes
  get 'employees/absence', to: 'absences#new', as: 'legacy_absence' #redirect old absence form route
  get 'employees/index', to: redirect('https://guides.library.ucmo.edu/employees') # redirect old employee directory
  get 'employees', to: redirect('https://guides.library.ucmo.edu/employees') # redirect old employee directory

  get 'scdps', to: 'employees#scdps'
  resources :employees, except: :index, param: :name do
    collection do
      get 'portal'
      get 'student-workers', to: 'employees#student_workers'
    end

    resources :absences do
      patch 'approve', on: :member
      patch 'reject', on: :member
      patch 'receive_note', on: :member
    end
  end
  get 'absences', to: 'absences#by_date', as: 'absences_by_date'
  get 'absences/:date', to: 'absences#by_date'

  resources :absences, only: [:new, :create, :index]


  # Contact routes REDIRECT
  resources :website_contacts, path: 'contact', only: [:create] do
    collection do
      get 'general'
      get 'employee/:name', action: 'employee', as: 'employee'
      get 'office/:name', action: 'office', as: 'office'
      get 'info'
    end
  end
  get 'contact', to: 'website_contacts#general'
  get 'contact/chat', to: 'website_contacts#chat'
  get 'chat', to: 'website_contacts#chat'

  # Map routes REDIRECT
  get 'map', to: 'map#index', as: 'map'
  get 'map/index', to: 'map#index'

  # Room booking routes
  get 'room-bookings', to: redirect('https://ucmo.libcal.com/reserve/jckl-rooms'), as: 'meeting_rooms' #old url redirect
  get 'roomschedules', to: redirect('https://ucmo.libcal.com/reserve/jckl-rooms') # old url redirect


  # New books routes REDIRECT
  resources :new_books, path: 'new-books', only: [:index] do
    get 'mappings', on: :collection
  end
  get 'newbooks', to: 'new_books#index'

  # Purchase request routes REDIRECT
  resources :new_book_requests, path: 'purchase-request', only: [:new, :create]
  get 'purchase-request', to: 'new_book_requests#new'

  # DVD routes REDIRECT
  get 'dvds', to: 'dvds#index', as: 'dvds'
  get 'dvds/index', to: 'dvds#index'

  # Stats routes
  get 'stats', to: 'stats#dashboard'
  get 'stats/dashboard', to: 'stats#dashboard', as: 'stats_dashboard'
  get 'stats/headcount_form', to: 'stats#headcount_form', as: 'stats_headcount_form'
  post 'stats/headcount_form', to: 'stats#headcount_form'
  get 'stats/headcounts', to: 'stats#headcounts', as: 'stats_headcounts'
  get 'stats/studyrooms', to: 'stats#studyrooms', as: 'stats_studyrooms'
  get 'stats/computers', to: 'stats#computers', as: 'stats_computers'

  # CLF routes
  get 'clf', to: redirect('http://clf.ucmo.edu')
  get 'clf/index', to: redirect('http://clf.ucmo.edu')
  get 'clf/books', to: 'clf#books_feed'
  get 'clf/browse'
  post 'clf/add_to_cart', as: 'clf_add_to_cart'
  get 'clf/cart', as: 'clf_cart'
  get 'clf/order', as: 'clf_order'
  post 'clf/order'

  # Tools routes
  get 'tools/callnumber-parser', to: 'tools#callnumber_parser'
  post 'tools/callnumber-parser', to: 'tools#callnumber_parser'
  post 'tools/calendar_sync', to: 'tools#calendar_sync'

  # File upload routes
  resources :files

  # Horses in Culture routes
  get 'horses_in_culture/data', to: 'horses_in_culture#data', as: 'horses_in_culture_data'

  # Error handling
  match '/401', to: 'errors#unauthorized', via: :all, as: 'error_unauthorized'
  match '/404', to: 'errors#not_found', via: :all, as: 'error_not_found'
  match '/422', to: 'errors#unprocessable', via: :all, as: 'error_unprocessable'
  match '/500', to: 'errors#internal_server_error', via: :all, as: 'error_internal_server_error'
  match '/ezproxy-error', to:'errors#ezproxy', via: :post, as: 'error_ezproxy'

  # Page element routes
  get 'api/ucm_header', to: 'api#ucm_header'
  get 'api/ucm_footer', to: 'api#ucm_footer'

  # API routes MERGE WITH ELEMENTS
  get 'api/nav', to: 'api#nav'

  # Assets handling
  get 'css/:file', to: 'assets#css'
  get 'js/:file', to: 'assets#js'
  get 'img/:file', to: 'assets#img'

  # Devise and ActiveAdmin authentication
  devise_config = ActiveAdmin::Devise.config
  devise_config[:controllers][:omniauth_callbacks] = 'omniauth_callbacks'
  devise_config[:controllers][:registrations] = 'devise/registrations'
  devise_config[:controllers][:sessions] = 'sessions'
  devise_for :users, devise_config
  ActiveAdmin.routes(self)
  get 'omniauth_callbacks/all'
end

app/models/website_contact.rb
class WebsiteContact < ApplicationRecord
  validates :contact_name, :contact_email, :subject, :message, presence: true

  def email_friendly_created_at
    created_at.to_formatted_s(:long_12hr)
  end
end

app/views/website_contacts/_form.erb
<div class="contact-form">
  <% if @contact_form.errors.any? %>
    <div class="form-errors alert alert-danger">
      <h2>Please correct the following errors:</h2>
      <ul>
        <% @contact_form.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= semantic_form_for(@contact_form, url: website_contacts_url ) do |f| %>
    <%= f.inputs do %>
      <%= f.input :contact_name, as: :string, label: "Your Name" %>
      <%= f.input :contact_email, as: :email, label: "Your Email Address" %>
      <%= f.input :contact_700_number, as: :string, label: "Your 700#" %>
      <% if action_name == "general" %>
        <%= f.input :topic, as: :select, label: "Topic of This Email",
        collection: {"General Library Questions" => "general", "Reference and Research Assistance" => "reference", "Comments and Suggestions" => "comments"} %>
      <% end %>
      <%= f.input :subject, as: :string %>
      <%= f.input :message, as: :text, input_html: { rows: "4" } %>
      <%= hidden_field_tag 'employee', @employee&.id %>
      <%= hidden_field_tag 'office', @office&.id %>
      <% #This is a honeypot for detecting spam %>
      <div class="honeypot">
        <%= label_tag :content %>
        <%= text_field_tag :content, nil %>
        <%= label_tag :last_name %>
        <%= text_field_tag :last_name, nil %>
        <%= label_tag :first_name %>
        <%= text_field_tag :first_name, nil %>
        <%= label_tag :username %>
        <%= text_field_tag :username, nil %>
      </div>
    <% end %>
    <%= f.actions do %>
      <%= f.action :submit, as: :button, label: "Submit", button_html: {class: 'btn btn-light'} %>
    <% end %>
  <% end %>
</div>

app/views/website_contacts/chat.html.erb
<h1><%= @page_title %></h1>

<div id="libchat_c93abd5e8053d934df9fbb88eb8a5782"></div>
<script src="//v2.libanswers.com/load_chat.php?hash=c93abd5e8053d934df9fbb88eb8a5782"></script>

app/views/website_contacts/employee.html.erb
<h1><%= @page_title %></h1>
<p>Complete this form to send an email to <%= @employee.first_last %>.</p>
<%= render "form" %>

app/views/website_contacts/general.html.erb
<h1><%= @page_title %></h1>
<p>Complete this form to send an email to JCKL. We will get back to you as quickly as possible.
  You can also email <a href="#" data-toggle="modal" data-target=".employee-list-modal">a specific employee</a>
  or <a href="#" data-toggle="modal" data-target=".office-list-modal">a specific library office</a>.</p>
<div class="employee-list-modal modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title">Select an Employee</h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="list-group">
          <% @employees.each do |employee| %>
            <%= link_to employee.last_first, employee_website_contacts_url(name: employee.url_slug), class: "list-group-item list-group-item-action" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="office-list-modal modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title">Select an Office</h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="list-group">
          <% @offices.each do |office| %>
            <%= link_to office.display_name, office_website_contacts_url(name: office.office_name), class: "list-group-item list-group-item-action" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render "form" %>

app/views/website_contacts/info.html.erb
<h1><%= @page_title %></h1>

<div class="list-group">
  <span class="list-group-item">
      <div class="libchat-widget-button" id="libchat_f84b4c05a5033a01d65116d4ae2db4fe"></div><script type="text/javascript" src="//v2.libanswers.com/load_chat.php?hash=f84b4c05a5033a01d65116d4ae2db4fe"></script>
  </span>
  <span class="list-group-item">
    Call us at 660-543-4283
  </span>
  <span class="list-group-item">
    Text us at 660-230-0011
  </span>
  <a href="http://guides.library.ucmo.edu" class="list-group-item">
    Research Guides and Tutorials
  </a>

  <a href="<%= subject_specialists_employees_path %>" class="list-group-item">
    Connect With Your Subject Specialist
  </a>
</div>

app/views/website_contacts/office.html.erb
<h1><%= @page_title %></h1>
<p>Complete this form to send an email to the <%= @office.display_name %>. You can also call <a href="tel:<%= @office.phone_number %>"><%= @office.phone_number %></a></p>
<%= render "form" %>